version: '3.1'

services:

  mongodb:
      image: mongo
      container_name: mongodb
      environment:
        - MONGODB_DATABASE=region
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
      ports:
        - 27017:27017
