version: '3.1'

services:

  mongodb:
      image: mongo
      container_name: mongodb
      environment:
        - MONGODB_DATABASE=region
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
      ports:
        - 27017:27017
  redis:
    image: redis
    container_name: redis-client
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    ports:
      - 6379:6379